# Generated by Django 5.2.5 on 2026-09-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBreakEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateField(null=True)),
                ('period', models.CharField(choices=[(10, '10 days'), (20, '20 days'), (55, '55 days')], max_length=10, null=True)),
                ('product_id', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
