services:

  nginx:
    build: ./compose/production/nginx
    image: 127.0.0.1:5000/rbzk_pro_nginx
    volumes:
      - staticfiles:/rbzk/staticfiles
      - mediafiles:/rbzk/mediafiles
    ports:
      - 80:80
      - 443:443
      - 5555:5555
      - 15672:15672
    depends_on:
      - web
      - flower

  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start
    image: 127.0.0.1:5000/rbzk_pro_web
    volumes:
      - staticfiles:/rbzk/staticfiles
      - mediafiles:/rbzk/mediafiles
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - redis
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - ./postgresData:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django

  redis:
    image: redis:6-alpine

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - ./.env/.prod-sample

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: 127.0.0.1:5000/rbzk_pro_celery_worker
    command: /start-celeryworker
    volumes:
      - staticfiles:/rbzk/staticfiles
      - mediafiles:/rbzk/mediafiles
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: 127.0.0.1:5000/rbzk_pro_celery_beat
    command: /start-celerybeat
    volumes:
      - staticfiles:/rbzk/staticfiles
      - mediafiles:/rbzk/mediafiles
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: 127.0.0.1:5000/rbzk_pro_celery_flower
    command: /start-flower
    volumes:
      - staticfiles:/rbzk/staticfiles
      - mediafiles:/rbzk/mediafiles
      - flower_db:/app/flower_db
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - redis
      - db

volumes:
  postgresData:
  staticfiles:
  mediafiles:
