# Generated by Django 5.2.5 on 2026-03-18 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('stop_requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('running_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coinbase.websockettask')),
            ],
        ),
    ]
