# Generated by Django 5.2.5 on 2026-04-07 23:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinbase_date', models.DateField(blank=True, max_length=1024, null=True)),
                ('ticker_symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('price_history', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), default=list, null=True, size=None)),
                ('high_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_atr', models.CharField(blank=True, help_text='N as Average True Range', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSocketTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('stop_requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('running_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coinbase.websockettask')),
            ],
        ),
    ]
