# Generated by Django 5.2.5 on 2026-04-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='daypricelog',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='daypricelog',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Close price', max_digits=24, null=True),
        ),
        migrations.CreateModel(
            name='BreakOutSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.IntegerField(choices=[(9, 'Byu'), (12, 'Sell')], default=-1)),
                ('ticker_symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('break_out_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('trend_direction', models.IntegerField(choices=[(3, 'Short'), (5, 'Long')])),
                ('trend_period', models.IntegerField(choices=[(-1, 'Stop Loss'), (10, 'Ten'), (20, 'Twenty'), (55, 'Fiftyfive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coinbase.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('state', models.IntegerField(choices=[(0, 'Closed'), (1, 'Open')])),
                ('type', models.IntegerField(choices=[(3, 'Short'), (5, 'Long')])),
                ('enter_price', models.DecimalField(decimal_places=12, max_digits=24, null=True)),
                ('stop_loss_price', models.DecimalField(decimal_places=12, max_digits=24, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('dollar_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('num_shares', models.DecimalField(blank=True, decimal_places=2, help_text='Shares purchased at enter price', max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buy_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_trades', to='coinbase.breakoutsignal')),
                ('sell_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_trades', to='coinbase.breakoutsignal')),
                ('trading_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coinbase.tradingpair')),
            ],
        ),
    ]
