# Generated by Django 5.2.5 on 2026-03-25 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinbase_date', models.DateField(blank=True, max_length=1024, null=True)),
                ('ticker_symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('price_history', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), default=list, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
