# Generated by Django 5.2.5 on 2026-04-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0002_strategy_breakoutsignal_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='high_price',
        ),
    ]
