# Generated by Django 5.2.5 on 2026-04-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0003_remove_trade_high_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
    ]
