# Generated by Django 5.2.5 on 2026-04-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0004_alter_trade_exit_price_alter_trade_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ticker_symbol',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
