# Generated by Django 5.2.5 on 2026-04-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0005_trade_ticker_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakoutsignal',
            name='ticker_symbol',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
