# Generated by Django 5.2.5 on 2026-04-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0006_breakoutsignal_ticker_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='dollar_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='num_shares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
    ]
