# Generated by Django 5.2.5 on 2026-04-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0007_trade_dollar_amount_trade_num_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='num_shares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shares purchased', max_digits=24, null=True),
        ),
    ]
