# Generated by Django 5.2.5 on 2026-04-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0008_alter_trade_num_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='num_shares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shares purchased at enter price', max_digits=24, null=True),
        ),
    ]
