# Generated by Django 5.2.5 on 2026-04-25 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0009_alter_trade_num_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='signal',
        ),
        migrations.AddField(
            model_name='breakoutsignal',
            name='signal_type',
            field=models.IntegerField(choices=[(9, 'Byu'), (12, 'Sell')], default=-1),
        ),
        migrations.AddField(
            model_name='trade',
            name='buy_signal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_trades', to='coinbase.breakoutsignal'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_signal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_trades', to='coinbase.breakoutsignal'),
        ),
        migrations.AlterField(
            model_name='breakoutsignal',
            name='trend_period',
            field=models.IntegerField(choices=[(-1, 'Stop Loss'), (10, 'Ten'), (20, 'Twenty'), (55, 'Fiftyfive')]),
        ),
    ]
