# Generated by Django 5.2.5 on 2026-04-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0010_remove_trade_signal_breakoutsignal_signal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daypricelog',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='daypricelog',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Close price', max_digits=24, null=True),
        ),
    ]
