# Generated by Django 4.2.13 on 2024-05-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateTimeField()),
                ('week_end', models.DateTimeField()),
                ('job_time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_start', models.DateTimeField()),
                ('job_end', models.DateTimeField()),
                ('notes', models.TextField()),
                ('workweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.workweek')),
            ],
        ),
    ]
