# Generated by Django 4.2.13 on 2024-05-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkjob',
            name='confirmation',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
