# Generated by Django 4.2.13 on 2024-05-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workweek',
            old_name='job_time',
            new_name='jobs_time',
        ),
    ]
