# Generated by Django 4.2.13 on 2025-01-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_parkjob_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2024, null=True)),
                ('email', models.CharField(blank=True, max_length=2024, null=True)),
                ('phone', models.CharField(blank=True, max_length=2024, null=True)),
                ('message', models.CharField(blank=True, max_length=2024, null=True)),
                ('navigators_match', models.BooleanField(default=False)),
                ('navigator_string_from_request', models.CharField(blank=True, max_length=2024, null=True)),
                ('navigator_string_from_js', models.CharField(blank=True, max_length=2024, null=True)),
            ],
        ),
    ]
