# Generated by Django 4.2.13 on 2024-05-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_job_time_workweek_jobs_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workweek',
            name='jobs_time',
            field=models.DurationField(null=True),
        ),
    ]
