# Generated by Django 4.2.13 on 2025-01-21 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_formsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
