# Generated by Django 4.2.13 on 2025-01-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_formsubmission_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
