# Generated by Django 4.2.13 on 2025-01-23 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_formsubmission_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 0, 23, 23, 847157, tzinfo=datetime.timezone.utc)),
        ),
    ]
