# Generated by Django 4.2.13 on 2025-01-23 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_formsubmission_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True),
        ),
    ]
