# Generated by Django 4.2.13 on 2025-07-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_squashed_0014_alter_formsubmission_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkjob',
            options={'ordering': ['-job_end']},
        ),
        migrations.AlterModelOptions(
            name='workweek',
            options={'ordering': ['-week_end']},
        ),
        migrations.AlterField(
            model_name='parkjob',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
