# Generated by Django 5.2.5 on 2026-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_parkjob_options_alter_workweek_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workweek',
            name='hourly_rate',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
