# Generated by Django 5.2.5 on 2026-05-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_workweek_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workweek',
            name='hourly_rate',
            field=models.IntegerField(default=1000, help_text='1 Dollar = 100 pennies', null=True),
        ),
    ]
