# Generated by Django 5.2.5 on 2026-08-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_workweek_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workweek',
            name='hourly_rate',
            field=models.IntegerField(default=1100, help_text='1 Dollar = 100 pennies', null=True),
        ),
    ]
