# Generated by Django 5.2.5 on 2026-09-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_workweek_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkjob',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
