# Generated by Django 5.2.5 on 2026-05-02 21:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakOutSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.IntegerField(choices=[(9, 'Byu'), (12, 'Sell')], default=-1)),
                ('ticker_symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('break_out_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('trend_direction', models.IntegerField(choices=[(3, 'Short'), (5, 'Long')])),
                ('trend_period', models.IntegerField(choices=[(-1, 'Stop Loss'), (10, 'Ten'), (20, 'Twenty'), (55, 'Fiftyfive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinbase_date', models.DateField(blank=True, max_length=1024, null=True)),
                ('ticker_symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('price_history', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), default=list, null=True, size=None)),
                ('open_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=12, help_text='Close price', max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_atr', models.CharField(blank=True, help_text='N as Average True Range', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebSocketTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('stop_requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(blank=True, max_length=1024, null=True)),
                ('state', models.IntegerField(choices=[(0, 'Closed'), (1, 'Open')])),
                ('type', models.IntegerField(choices=[(3, 'Short'), (5, 'Long')])),
                ('enter_price', models.DecimalField(decimal_places=12, max_digits=24, null=True)),
                ('stop_loss_price', models.DecimalField(decimal_places=12, max_digits=24, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('dollar_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('num_shares', models.DecimalField(blank=True, decimal_places=2, help_text='Shares purchased at enter price', max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buy_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_trades', to='cb_mark.breakoutsignal')),
                ('sell_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_trades', to='cb_mark.breakoutsignal')),
                ('trading_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cb_mark.tradingpair')),
            ],
        ),
        migrations.AddField(
            model_name='breakoutsignal',
            name='trading_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cb_mark.tradingpair'),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='running_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cb_mark.websockettask'),
        ),
    ]
