# Generated by Django 5.2.5 on 2026-05-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='num_shares',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Shares purchased at enter price', max_digits=24, null=True),
        ),
    ]
