# Generated by Django 5.2.5 on 2026-05-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mark', '0002_alter_trade_num_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='highest_10day',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='highest_20day',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='highest_55day',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='lowest_10day',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='lowest_20day',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='lowest_55day',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
    ]
