# Generated by Django 5.2.5 on 2026-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mark', '0003_tradingpair_highest_10day_tradingpair_highest_20day_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Strategy',
        ),
        migrations.RemoveField(
            model_name='tradingpair',
            name='running_task',
        ),
        migrations.AddField(
            model_name='trade',
            name='uid',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='WebSocketTask',
        ),
    ]
