# Generated by Django 5.2.5 on 2026-09-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mark', '0004_delete_strategy_remove_tradingpair_running_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='decimal_places',
            field=models.IntegerField(default=2, max_length=12),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='ticker_symbol',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
