# Generated by Django 5.2.5 on 2026-09-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mark', '0005_tradingpair_decimal_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='ticker_symbol',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
