# Generated by Django 5.2.5 on 2026-09-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mark', '0006_alter_tradingpair_ticker_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='decimal_places',
            field=models.IntegerField(default=2),
        ),
    ]
