# Generated by Django 5.2.5 on 2026-09-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mark', '0007_alter_tradingpair_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakoutsignal',
            name='signal_type',
            field=models.IntegerField(choices=[(-1, 'Stop Loss'), (9, 'Byu'), (12, 'Sell')], default=-1),
        ),
    ]
