#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /rbzk/manage.py collectstatic --noinput
python /rbzk/manage.py migrate

/usr/local/bin/gunicorn rbzk.asgi:application --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker \
    --access-logfile=/rbzk/logs/access.log \
    --error-logfile=/rbzk/logs/error.log  \
    --chdir=/rbzk

    # remember that the error was missing backslashes the command above

# /usr/local/bin/gunicorn \
#     --bind 0.0.0.0:443 rbzk.wsgi:application  \
#     --chdir=/rbzk  \
#     --workers=2   \
#     --certfile=/rbzk/compose/production/nginx/certs/rbzk_pro.crt  \
#     --keyfile=/rbzk/compose/production/nginx/certs/rbzk_pro.key \
#     --ca-certs=/rbzk/compose/production/nginx/certs/cert_chain.crt \
#     --access-logfile=/rbzk/logs/access.log --error-logfile=/rbzk/logs/error.log \
#     --daemon \
