#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /rbzk/manage.py collectstatic --noinput
python /rbzk/manage.py migrate

/usr/local/bin/gunicorn rbzk.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --chdir=/rbzk