#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /rbzk/manage.py collectstatic --noinput
python /rbzk/manage.py migrate

# /usr/local/bin/gunicorn rbzk.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --chdir=/rbzk
/usr/local/bin/gunicorn rbzk.wsgi:application --workers=2 --bind 0.0.0.0:443 --chdir=/rbzk --certfile=/rbzk/compose/production/nginx/certs/rbzk_pro.crt --keyfile=/rbzk/compose/production/nginx/certs/rbzk_pro.key
#   --chdir=/rbzk \
#   --workers=2  \
#   --certfile=/rbzk/compose/production/nginx/certs/rbzk_pro.crt \
#   --keyfile=/rbzk/compose/production/nginx/certs/rbzk_pro.key \
#   --daemon \
#   --ca-certs=/rbzk/compose/production/nginx/certs/cert_chain.crt \
#   --access-logfile=/rbzk/logs/access.log --error-logfile=/rbzk/logs/error.log \